### ISSUE TITLE
add fmt 7 installer.

### ISSUE THREAD

**Issue by HerXayah** [MGThePro/yuzu-EA-compiler#3]
add

```
git clone https://github.com/fmtlib/fmt
cd fmt
mkdir build
cd build
cmake ..
sudo make install
```

EDIT: If you run yuzu it complains that it cant find fmt7 and fmt6 doesnt work here

**Comment by MGThePro** [comment]
So far building and running on fmt 6.2.1-3 hasn't been an issue for me, and compiling an additional dependency inside the PKGBUILD is really not something I'd like to do. Additionally, fmt is already flagged out of date on the arch repository, they'll probably update it fairly soon. I'll just leave this issue open for now in case anyone has issues building yuzu with fmt 6, the maintainer will hopefully update it soon enough
